SELECT 
        DET.ID_EVENTO_ATENCAO_SAUDE,
        DET.DT_REALIZACAO,
        DET.CD_PROCEDIMENTO,
        DET.CD_TABELA_REFERENCIA,
        DET.QT_ITEM_EVENTO_INFORMADO,
        DET.VL_ITEM_EVENTO_INFORMADO,
        CONS.ID_PLANO,
        CONS.FAIXA_ETARIA,
        CONS.SEXO,
        CONS.CBO,
        operadoras.CD_PLANO,
        operadoras.NM_PLANO,
        operadoras.CD_OPERADORA,
        operadoras.RAZAO_SOCIAL,
        operadoras.SGMT_ASSISTENCIAL,
        operadoras.SITUACAO_PLANO

FROM operadoras
INNER JOIN CONS ON CONS.ID_PLANO = operadoras.ID_PLANO
INNER JOIN DET ON DET.ID_EVENTO_ATENCAO_SAUDE = CONS.ID_EVENTO_ATENCAO_SAUDE
    AND DET.CD_PROCEDIMENTO IN (40302075, 40302733)
WHERE CD_OPERADORA = 417599

